name: Deploy to HuggingFace Spaces

on:
 push:
   branches:
     - main
 workflow_dispatch:

jobs:
 sync-to-huggingface:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
         lfs: true

     - name: Push to HuggingFace Space
       env:
         HF_TOKEN: ${{ secrets.HF_TOKEN }}
       run: |
         # Install Git LFS
         git lfs install

         # Configure git
         git config --global user.email "richard.stoker@usda.gov"
         git config --global user.name "richtext"
         git config --global commit.gpgsign false
         

         # Add HuggingFace remote
         git remote add huggingface https://huggingface.co/spaces/richtext/Food-Database-Mapper

         # Push to HuggingFace using the token
         git push https://HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/richtext/Food-Database-Mapper main --force
